### PR TITLE
Fix #706: Failing test testCreateApplicationWithDuplicateName

### LINKED ISSUE #706: Failing test testCreateApplicationWithDuplicateName
Following error occurs during build:

```
[ERROR] Failures: 
[ERROR]   CreateApplicationTest.testCreateApplicationWithDuplicateName:56 Unexpected exception type thrown ==> expected: <org.springframework.dao.DataIntegrityViolationException> but was: <io.getlime.security.powerauth.app.server.service.exceptions.GenericServiceException>
```

### PR DESCRIPTION
**Pull request by romanstrobl**
The build succeeds now.

### CODE REVIEW

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java [hunk 1]
```diff
@@ -53,7 +53,7 @@ public void testCreateApplicationWithDuplicateName() {
         CreateApplicationRequest request = new CreateApplicationRequest();
         request.setApplicationId(testId);
         assertDoesNotThrow(()-> powerAuthService.createApplication(request));
-        assertThrows(DataIntegrityViolationException.class, ()-> powerAuthService.createApplication(request));
+        assertThrows(GenericServiceException.class, ()-> powerAuthService.createApplication(request));
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java:56]: Are we really using default formatter? Because in that case it should be `() ->`

**Review by banterCZ — APPROVED** [review]

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java (hunk 1 above)
Comment (banterCZ) [reply powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/CreateApplicationTest.java]: Great! If we are already touching the line, why not to make it perfect? ;)

**Review by petrdvorak — APPROVED** [review]
Looks good
