### PR TITLE
Fix #1644: Investigate error on Base64 decoding in challenge

### LINKED ISSUE #1644: Investigate error on Base64 decoding in challenge
We noticed the following error:

```
Illegal base64 character 2d (through reference chain: com.wultra.powerauth.fido2.rest.model.entity.CollectedClientData["challenge"])
```

We only saw it once when using `CZFlotantă žluťoučký koníček` as IBAN value, and we are now unable to reproduce the issue with the data.

### PR DESCRIPTION
**Pull request by jnpsk**
Challenge is encoded to Base64Url on the browser level. The encoded challenge is then encapsulated to the [Collected Client Data structure](https://www.w3.org/TR/webauthn-3/#dictionary-client-data), which hash is later signed by the authenticator. Base64Url decoding should be applied on the challenge during the CollectedClientData deserialization.

### CODE REVIEW

File: powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToStringDeserializer.java [hunk 1]
```diff
@@ -64,7 +64,7 @@ public Base64ToStringDeserializer(Class<?> vc) {
     @Override
     public String deserialize(JsonParser jsonParser, DeserializationContext deserializationContext) throws Fido2DeserializationException {
         try {
-            return new String(Base64.getDecoder().decode(jsonParser.getText()), StandardCharsets.UTF_8);
+            return new String(Base64.getUrlDecoder().decode(jsonParser.getText()), StandardCharsets.UTF_8);
```
Comment (banterCZ) [inline powerauth-fido2/src/main/java/com/wultra/powerauth/fido2/rest/model/converter/serialization/Base64UrlToStringDeserializer.java:67]: 👍

**Review by banterCZ — APPROVED** [review]
Looks good.

**Review by zcgandcomp — APPROVED** [review]
Looks OK.
