### PR TITLE
Fix #439: Improve exception logging in the REST controller

### LINKED ISSUE #439: Improve exception logging in the REST controller

### PR DESCRIPTION
**Pull request by petrdvorak**

### CODE REVIEW

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTResponseExceptionResolver.java [hunk 1]
```diff
@@ -54,6 +58,10 @@ public RESTResponseExceptionResolver() {
     @Nullable
     protected ModelAndView doResolveException(@NonNull HttpServletRequest request, @NonNull HttpServletResponse response, @Nullable Object handler, @NonNull Exception exception) {
         try {
+
+            // Log the exception
+            logger.warn("An exception occurred in Spring Framework while processing the request.", exception);
```
Comment (romanstrobl) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTResponseExceptionResolver.java:63]: We do not usually put a period at the end of log messages.

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTResponseExceptionResolver.java [hunk 2]
```diff
@@ -84,6 +92,7 @@ protected ModelAndView doResolveException(@NonNull HttpServletRequest request, @
             response.flushBuffer();
         } catch (IOException e) {
             // Response object does have an output stream here
+            logger.error("An exception occurred while serializing JSON error response.", e);
```
Comment (romanstrobl) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/controller/RESTResponseExceptionResolver.java:95]: dtto

**Comment by petrdvorak** [comment]
Fixed.
