### PR TITLE
Fix #762: Insufficient input validation in activation prepare endpoint

### LINKED ISSUE #762: Insufficient input validation in activation prepare endpoint
By accident I found a wrong input validation in `/rest/v3/activation/prepare` endpoint if mobile client doesn't send valid JSON in encrypted data. For example, if `devicePublicKey` is missing, then the following crash is reported:
```
java.lang.NullPointerException: null
	at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:889) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding$StandardBaseEncoding.trimTrailingPadding(BaseEncoding.java:675) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding.decodeChecked(BaseEncoding.java:232) ~[guava-31.0.1-jre.jar:na]
	at com.google.common.io.BaseEncoding.decode(BaseEncoding.java:217) ~[guava-31.0.1-jre.jar:na]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior.prepareActivation(ActivationServiceBehavior.java:888) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior$$FastClassBySpringCGLIB$$ed6eb169.invoke(<generated>) ~[classes/:1.2.5]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:689) ~[spring-aop-5.3.18.jar:5.3.18]
	at io.getlime.security.powerauth.app.server.service.behavior.tasks.v3.ActivationServiceBehavior$$EnhancerBySpringCGLIB$$35bd738c.prepareActivation(<generated>) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl.prepareActivation(PowerAuthServiceImpl.java:314) ~[classes/:1.2.5]
	at io.getlime.security.powerauth.app.server.service.v3.PowerAuthServiceImpl$$FastClassBySpringCGLIB$$9b67a966.invoke(<generated>) ~[classes/:1.2.5]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:783) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.3.18.jar:5.3.18]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:753) ~[spring-aop-5.3.18.jar:5.3.18]
        ...etc...
```

It's also strange that HTTP response is 500 (that's correct), but the formatted error doesn't fit to our specification:
```json
{
	"timestamp": "2022-09-08T19:21:03.132+00:00",
	"status": 500,
	"error": "Internal Server Error",
	"path": "/powerauth-java-server/rest/v3/activation/prepare"
}
```
I don't know if this is OK or not. The mobile client will perhaps properly get the correct error, due to an additional processing at RESTful integration layer.

### PR DESCRIPTION
**Pull request by jnpsk**
The encrypted payload represents ActivationLayer2Request.class, which contains:

- devicePublicKey (expected)
- activationOtp, platform (have logic based on null value later)
- non-specific activationName, extras, deviceInfo

Test case was created to replicate the issue and the issue was solved by checking of presence of the devicePublicKey, which is the only attribute passed directly to a method without being checked.

### CODE REVIEW

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java [hunk 1]
```diff
@@ -906,6 +906,14 @@ public PrepareActivationResponse prepareActivation(String activationCode, String
                 throw localizationProvider.buildExceptionForCode(ServiceError.INVALID_INPUT_FORMAT);
             }
 
+            // Ensure presence of the devicePublicKey
+            final String retrievedDevicePublicKey = request.getDevicePublicKey();
+            if (retrievedDevicePublicKey == null || retrievedDevicePublicKey.isEmpty()) {
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java:911]: What about simplifying with `StringUtils#hasText(String)`?

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java [hunk 2]
```diff
@@ -906,6 +906,14 @@ public PrepareActivationResponse prepareActivation(String activationCode, String
...
+                logger.warn("Invalid activation request, activation code: {}", activationCode);
+                // Rollback is not required, error occurs before writing to database
+                throw localizationProvider.buildExceptionForCode(ServiceError.INVALID_REQUEST);
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java:914]: This error code `INVALID_REQUEST` is inconsistent with `INVALID_INPUT_FORMAT` used at https://github.com/wultra/powerauth-server/pull/970/files#diff-a4ce67a9fd8bc9dfacab0302fa5f1cb1a44ee59e9ceafb746ef9e8df877d7492R1162

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 3]
```diff
@@ -0,0 +1,98 @@
+package io.getlime.security.powerauth.app.server.service.behavior.tasks;
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:1]: Missing copyright header.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 4]
```diff
@@ -0,0 +1,98 @@
...
+import java.security.PublicKey;
+import java.security.interfaces.ECPublicKey;
+import java.util.Base64;
+import java.util.Date;
+import java.util.UUID;
+
+import static org.junit.jupiter.api.Assertions.*;
+
+@SpringBootTest
+public class ActivationServiceBehaviorTest {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:41]: Missing Javadoc at least with the `@author` tag.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 5]
```diff
@@ -0,0 +1,98 @@
...
+    @Autowired
+    private PowerAuthService powerAuthService;
+
+    private final KeyConvertor keyConvertor = new KeyConvertor();
+
+    @Test
+    void testPrepareActivation() throws Exception {
+        // Testing validation of encrypted data, sent in activation prepare endpoint.
+
+        String testId = UUID.randomUUID().toString();
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:55]: Let's use the `final` modifier where possible.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 6]
```diff
@@ -0,0 +1,98 @@
...
+                createApplicationVersionResponse.getApplicationSecret().getBytes(StandardCharsets.UTF_8),
+                EciesSharedInfo1.ACTIVATION_LAYER_2, eciesParameters);
+        ByteArrayOutputStream baos = new ByteArrayOutputStream();
+        new ObjectMapper().writeValue(baos, requestL2);
+        EciesPayload eciesPayload = eciesEncryptor.encrypt(baos.toByteArray(), eciesParameters);
+
+
+        Executable executable = () -> tested.prepareActivation(activationCode, applicationKey,
+                shouldGenerateRecoveryCodes, eciesPayload, version, this.keyConvertor);
+        GenericServiceException exception = assertThrows(GenericServiceException.class, executable);
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:94]: Just a matter of taste, but could be inlined.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 7]
```diff
@@ -0,0 +1,98 @@
...
+        assertEquals(ServiceError.INVALID_REQUEST, exception.getCode());
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:95]: Thanks for the test, but I would expect also a happy day scenario.

**Review by banterCZ — COMMENTED** [review]
Thanks for a very promising draft. First of all, please sign your commits as described at https://github.com/wultra/.github/blob/main/CONTRIBUTING.md Also please link the issue from the commit message. Last, but not least, please add _a happy day_ test case.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 8]
```diff
@@ -0,0 +1,178 @@
...
+    private ActivationServiceBehavior tested;
+
+    @Autowired
+    private PowerAuthService powerAuthService;
+
+    private final KeyConvertor keyConvertor = new KeyConvertor();
+    private final String version = "3.2";
+
+    @Test
+    public void testPrepareActivationWithValidPayload() throws Exception {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:73]: Let's stick with the _default package visibility_ please https://rules.sonarsource.com/java/RSPEC-5786/ (class and methods).

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 9]
```diff
@@ -0,0 +1,178 @@
...
+
+        // Generate public key for a client device
+        final KeyGenerator keyGenerator = new KeyGenerator();
+        final KeyPair keyPair = keyGenerator.generateKeyPair();
+        final byte[] publicKeyBytes = keyConvertor.convertPublicKeyToBytes(keyPair.getPublic());
+
+        // Create request payload
+        final ActivationLayer2Request requestL2 = new ActivationLayer2Request();
+        requestL2.setDevicePublicKey(Base64.getEncoder().encodeToString(publicKeyBytes));
+        final EciesPayload correctEciesPayload = this.buildPrepareActivationPayload(requestL2, detailResponse);
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:92]: `this.` is not needed at all in the whole test class.

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java [hunk 10]
```diff
@@ -1146,8 +1155,16 @@ public CreateActivationResponse createActivation(
                 throw localizationProvider.buildRollbackingExceptionForCode(ServiceError.INVALID_INPUT_FORMAT);
             }
 
+            // Ensure presence of the devicePublicKey
+            final String retrievedDevicePublicKey = request.getDevicePublicKey();
+            if (!StringUtils.hasText(retrievedDevicePublicKey)) {
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java:1160]: Just note that this branch is not covered by the test case (I do not know whether it is on purpose or by mistake). Not sure, but extracting a validation method could be helpful.

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java [hunk 11]
```diff
@@ -1695,6 +1712,14 @@ public RecoveryCodeActivationResponse createActivationUsingRecoveryCode(Recovery
                 throw localizationProvider.buildExceptionForCode(ServiceError.INVALID_INPUT_FORMAT);
             }
 
+            // Ensure presence of the devicePublicKey
+            final String retrievedDevicePublicKey = layer2Request.getDevicePublicKey();
+            if (!StringUtils.hasText(retrievedDevicePublicKey)) {
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehavior.java:1717]: dtto - test coverage

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 12]
```diff
@@ -0,0 +1,178 @@
...
+
+import static org.junit.jupiter.api.Assertions.*;
+
+/**
+ * Test for {@link ActivationServiceBehavior}.
+ *
+ * @author Jan Pesek, janpesek@outlook.com
+ */
+@SpringBootTest
+@Transactional
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:60]: This type of test against the database is not wrong. Just a question. Have you considered using `@MockBean`? Of course, there are some disadvantages https://www.baeldung.com/spring-tests#2-the-problems-withmockbean

**Review by banterCZ — COMMENTED** [review]
Thanks for reflecting on my comments but I still have not noticed that your commits are signed, see https://github.com/wultra/.github/blob/main/CONTRIBUTING.md

**Review by romanstrobl — APPROVED** [review]
I did not find any additional issues.

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryCodeEntity.java [hunk 13]
```diff
@@ -72,7 +72,7 @@ public class RecoveryCodeEntity implements Serializable {
     @Column(name = "timestamp_created", nullable = false)
     private Date timestampCreated;
 
-    @Column(name = "timestamp_last_used", nullable = false)
+    @Column(name = "timestamp_last_used")
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/RecoveryCodeEntity.java:75]: Nice catch! We should investigate deeper.

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 14]
```diff
@@ -0,0 +1,395 @@
...
+        final String activationId = initActivationResponse.getActivationId();
+
+        assertEquals(ActivationStatus.CREATED, getActivationStatus(activationId));
+
+        // Create request payload, omit device public key
+        final ActivationLayer2Request requestL2 = new ActivationLayer2Request();
+        final EciesPayload invalidEciesPayload = buildPrepareActivationPayload(requestL2, detailResponse);
+
+        // Prepare activation with missing devicePublicKey
+        GenericServiceException exception = assertThrows(
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:117]: May be `final`.
```suggestion
        final GenericServiceException exception = assertThrows(
```

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 15]
```diff
@@ -0,0 +1,395 @@
...
+import static org.junit.jupiter.api.Assertions.*;
+
+/**
+ * Test for {@link ActivationServiceBehavior}.
+ *
+ * @author Jan Pesek, janpesek@outlook.com
+ */
+@SpringBootTest
+@Transactional
+public class ActivationServiceBehaviorTest {
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:59]: Could be _package private_.
```suggestion
class ActivationServiceBehaviorTest {
```

File: powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java [hunk 16]
```diff
@@ -0,0 +1,395 @@
...
+import com.wultra.security.powerauth.client.model.response.*;
+import io.getlime.security.powerauth.app.server.service.PowerAuthService;
+import io.getlime.security.powerauth.app.server.service.exceptions.GenericServiceException;
+import io.getlime.security.powerauth.app.server.service.model.ServiceError;
+import io.getlime.security.powerauth.app.server.service.model.request.ActivationLayer2Request;
+import io.getlime.security.powerauth.app.server.service.model.response.ActivationLayer2Response;
+import io.getlime.security.powerauth.crypto.lib.encryptor.ecies.EciesDecryptor;
+import io.getlime.security.powerauth.crypto.lib.encryptor.ecies.EciesEncryptor;
+import io.getlime.security.powerauth.crypto.lib.encryptor.ecies.EciesEnvelopeKey;
+import io.getlime.security.powerauth.crypto.lib.encryptor.ecies.EciesFactory;
```
Comment (banterCZ) [inline powerauth-java-server/src/test/java/io/getlime/security/powerauth/app/server/service/behavior/tasks/ActivationServiceBehaviorTest.java:33]: I am sorry, but meanwhile `EciesFactory` was replaced by `EncryptorFactory`. SNAPSHOT not published yet, see https://github.com/wultra/powerauth-server/pull/965 But we may fix it later on before merging.

**Review by banterCZ — APPROVED** [review]
Well done. Changes in the develop branch were quite extensive, so we have to reflect them here before merging.
