### PR TITLE
Fix #890: AttributeConverter dirty checking does not work at Hibernate 6

### LINKED ISSUE #890: AttributeConverter dirty checking does not work at Hibernate 6
See https://hibernate.atlassian.net/browse/HHH-16081

### PR DESCRIPTION
**Pull request by banterCZ**

### CODE REVIEW

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/converter/ListConverterMutabilityPlan.java [hunk 1]
```diff
@@ -0,0 +1,54 @@
...
+import java.io.Serializable;
+import java.util.ArrayList;
+import java.util.List;
+
+/**
+ * // TODO (racansky, 2023-04-17, https://hibernate.atlassian.net/browse/HHH-16081) workaround for non working-dirty checking
+ *
+ * @author Lubos Racansky, lubos.racansky@wultra.com
+ */
+public class ListConverterMutabilityPlan implements MutabilityPlan<List<String>> {
```
Comment (banterCZ) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/converter/ListConverterMutabilityPlan.java:32]: - [ ] Better rewrite to `MutableMutabilityPlan`.

**Review by romanstrobl — APPROVED** [review]
Good solution.
