### PR TITLE
Fix #1538: DB migration issue (MS SQL, possible Oracle)

### LINKED ISSUE #1538: DB migration issue (MS SQL, possible Oracle)
Step to reproduce
Install version prior to 1.7.x
Create activation
Migrate to 1.7.x

Expected behavior:
The record in the table `pa_activation` has "powerauth" in the column `protocol`.

Actual behavior:
The record in the table `pa_activation` has an empty column `protocol` on MS SQL. 

The null value leads to:

```
Runtime exception or error occurred, transaction will be rolled back

java.lang.NullPointerException: Cannot invoke "java.lang.String.toUpperCase()" because the return value of "io.getlime.security.powerauth.app.server.database.model.entity.ActivationRecordEntity.getProtocol()" is null
```
when calling API
`GET {{powerauth_url}}/v2/registrations?userId={user_id}`

### PR DESCRIPTION
**Pull request by banterCZ**
This is a fix into 1.7.x; for develop, we will make the column not-null, see #1544

### CODE REVIEW

File: powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java [hunk 1]
```diff
@@ -667,6 +669,16 @@ public List<ActivationHistoryEntity> getActivationHistory() {
         return activationHistory;
     }
 
+    @PostLoad
+    public void setDefaultProtocol() {
```
Comment (zcgandcomp) [inline powerauth-java-server/src/main/java/io/getlime/security/powerauth/app/server/database/model/entity/ActivationRecordEntity.java:673]: This is a fix for null values in the DB. But the null values are updated in the liquibase script.

**Review by zcgandcomp — CHANGES_REQUESTED** [review]

**Comment by banterCZ** [comment]
- [ ] Let's make the column _not-null_ even for backport

**Review by romanstrobl — APPROVED** [review]
Good fix.
